### ISSUE TITLE
Update of dependencies/repositories on devices flow

### ISSUE THREAD

**Issue by chloeskt** [pyronear/pyro-sys-setup#7]
Hi everyone ! 

## Motivation: update of repositories on devices

We need to discuss the flow of updates ! Here are my first thoughts on this process. I’d be glad to read your thoughts in this issue ! 

### On master device

What are the possible things to be updated ? 
- pyro-engine as a repo i.e. the source code is ON the master rpi
- pyro-vision as a package i.e. the source code is NOT ON the master rpi, it is only a library
- … ? 

How could it be updated ?
- if repo, either:
    - DL the new source code using the tag or the hash of the commit for a given repo (in that case, we need to be careful with the .env file for instance, needs to be outside the repo so as not to be erased when DL again the source code)
    - use git (installed on the rpi) to pull the diff
- if package: pip install latest version

How is the hash computed ?
- if we have only one repo: take the latest tag or the latest hash of the commit
- if we have multiple repo (the case for us I think): we need to have a way to know which repo needs to be updated !! For that I see a solution:
    - we add a parameter to the route in the API: the name of the repo for instance. The master rpi checks for all the repos it uses the hash it should have and compare it to the hash it currently has. Now if the repo needs to be updated, the rpi knows which repo it is. It does not have to update all the repos. 

### On camera device

What are the possible things to be updated ? 
- script to take picture
- script to monitor the device (temp, etc)

How could it be updated ? 
- Master rpi gets the new script somehow 
- Master rpi ssh over camera device (for that we need to know IN ADVANCE what the ip addresses of the camera rpis are - probably need to open an issue on that)
- New script is copy/paste on camera device

## More general comments

Not necessary to use Ansible. Python scripts or bash scripts in cron jobs should be enough and probably simpler.

**Comment by fe51** [comment]
Hi Chloé, thanks for opening the issue !

### About tools we want to be able to be updated

- pyro-engine indeed —> so quite easy to update
- pyro-vision : eventually the package is only a dependance in pyro-engine. 
  The only thing to keep updated is the version of torch and torchvision computed for ARM 
  - Either we decide to not update version now (in the scope of the MVP) --> seems reasonable but need to validate this point with vision team
  - Or, we can when looking fo updates, identify the latest version of those builds in the lastest pyro-vision release, and updates consequently --> seems feasible
  - Or look in pyro-vision realeases for the version asked in pyro-engine requirements, and download it --> seems feasible

### About the how

- Okay with your propositions (repo or package)

- Good point about the .env ! 

### About hashing

Is having on central git really heavy ? (Sounds easier but DL source code is okay as well)

However, might be a bit more complicated when there is more than one repo/package.

So far, in the case of the MVP, we might only have direct dependance to pyro-engine. what do you think ? 
And there could be a workaround to update pyro-engine, then, in the "updating process", update some requirements files (specifying which other dependences to update --> do you see my point ?)

But more general use case might need to be considered. With multiple repo, the API should not have a parameter for each potential dependance ... except if we consider storing a dict of repo:hash as hash .. why not..


### Updating camera devices :

Let us consider we only need to update these two scripts ( not adding a new script ) 

I was thinking it not so complicated to set up a fixed IP address, and it must be handled over an issue as long the central pi must have a fix address if we want pi camera to reach the webserver. What do you think ?

Hence, I am okay with you suggestion

- pi camera scripts are in pyro-engine, so by updating pyro-engine, we update those scripts
- Copy paste (by scp / ssh)
- **Plus**, need to handle updates dependencies (would be in a specific req file)of these scripts  (install on central and copy paste to pi cameras ? and install as well ? )



### About using ansible

About using ansible, some parts are easier only with python/bash but to handle the pi caméra addresses and credentials, it would maybe easier to handle the fleet with ansible. But I implies to set up ansible on central pi as well, but sounds feasible. 



### Eventually, to update the fleet (adding or revoking a pi camera...)

- revoking a camera. It might be handled by a new route on pyro-api/device (we store on device table, the list of the children of the central pi ..) to retrieve the pi camera id list, and update the local fleet consequently (by updating the config file hardcoded with devices ids and credentials --> not so much discussed and designed ) 
- However, adding a pi implies to be able to retrieve creds from another devices in the api.. seems not possible to me —> a dirty workaround would be, by default set like 10 children devices for a central pi device, hence, we would have some jokers in the case of adding a pi. (And these perimeter would be properly updated when we go physically on site ...)

**Comment by fe51** [comment]
I will open the fleet update in another issue!

**Comment by chloeskt** [comment]
Hi @fe51, 

- Yes we need to update torchvision and pytorch (cf this [playbook](https://github.com/pyronear/pyro-sys-setup/blob/scripts_monitor_vision/playbooks/install_vision_dependencies.yml) and enforce the versions of these two packages when installing pyro-vision (we might not be able to just use the requirements of pyro-engine directly, did not check that yet but there will probably be some issues).
- In the case of having multiple repos, if the API does not have another parameter how will the rpi which repo to update ? My point is the following: let's say we have 3 repos thus 3 hashes. To get a unique hash we can either:
        - compute the hash of the hashes: but then the rpi does not know which repo needs to be updated if the hash changes.
        - concatenate hash1-hash2-hash3 (always in the same order !!): in that case, we compare the three hashes separetely and the rpi knows which repo to update (but I don't think this very clean)
- another solution is to have a parameter in the route which corresponds to the name of the repo and each repo gets its hash (cleaner for me)
- I don't think that Git is very heavy. In addition, we would need to be careful on what goes on the branch master. My suggestion would be to create another branch dedicated to what needs to be on the rpi and only update this branch when we are sure of what we are doing.
- To get fixed IP adresses that might be more complicated. On creation of the device you can always ask the rpi to take a certain IP adress but it might be that this IP is already taken on the local network at the physical installation point (i.e. les "tours"). Ideally we should have a local network with ONLY our fleet of rpi on, otherwise we will be in a bad position 😅 For the main rpi, as it will have internet, it can always find its ip address and send it to a remote server (provided that we put a script in a cron job to do so). But for the rpi with camera that's a more complicated story ... in order to ssh on the main rpi to send their ip addresses, they need to know the IP address of the main rpi which might have changed if the IP address that we enforced was already taken ... To sum up, we should only have our rpis on the local network (i.e. connected to the switch).
- One other solution which might be possible: have a DNS for each rpi (for instance `raspberrymaster`, `rpicamera1`, `rpicamera2`, ... and we would then use `raspberrymaster.local` etc so as not to use the ip addresses ... That's not garantee to work and we could use nmap as back-up (see [this](https://www.raspberrypi.org/documentation/remote-access/ip-address.md)). 
- **Anyways I think that this IP adress issue is way more important than the rest, we ABSOLUTELY need to be able to communicate with the rpis from the outside, without having to go on site. And I think that that's a more complicated issue than it seems.**
- To handle updates on the rpi with camera we could use Ansible (installed and ran on the main rpi yes) and all these tasks will be linked to cron jobs.
